# Generated by Django 3.1.7 on 2021-03-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20210307_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='sns_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
